const ACTIONS = {
  JOIN: "JOIN",
  NEWUSERJOINED: "NEWUSERJOINED",
  DISCONNECTED: "DISCONNECTED",
  LEAVE: "LEAVE",
  "OBJECT:MOVING": "OBJECT:MOVING",
  "OBJECT:SCALING": "OBJECT:SCALING",
  "OBJECT:ROTATING": "OBJECT:ROTATING",
  "OBJECT:REMOVED": "OBJECT:REMOVED",
  "OBJECT:ADDED": "OBJECT:ADDED",
  "TEXT:CHANGED": "TEXT:CHANGED",
};

export { ACTIONS };
